server:
  port: 5221

spring:
  data:
      mongodb:
        host: ${MONGO_IP}
        port: ${MONGO_PORT}
        username: ${MONGO_BRIDGE_USER}
        password: ${MONGO_BRIDGE_PW}
        database: evaluation

idealobridge:
  oAuth2ClientId: ${CLIENT_ID}
  oAuth2ClientSecret: ${CLIENT_SECRET}
  accessTokenURI: ${ACCESS_TOKEN_URI}
  apiUrl: ${API_URL}
  sampleOffersRoute: "/sampleOffers/"
  shopIDToRootUrlRoute: "/rootUrl/"